### ISSUE TITLE
Database sync bug (updateExplorer chan *chainhash.Hash closed prematurely)

### ISSUE THREAD

**Issue by dmigwi** [decred/dcrdata#1005]
@chappjc I was almost done with full db sync from scratch on master branch since yesterday when the following error occurred. Got clues on the possible causes?

In the meantime I will be looking into it.
```
2019-02-13 19:46:43.820 [INF] PSQL: Updating from vins 13100000 to 13199999...
2019-02-13 19:54:06.144 [INF] PSQL: Updating from vins 13200000 to 13299999...
2019-02-13 20:01:23.843 [INF] PSQL: Updating from vins 13300000 to 13399999...
2019-02-13 20:08:46.034 [INF] PSQL: Updating from vins 13400000 to 13499999...
2019-02-13 20:15:33.692 [INF] PSQL: Updating from vins 13500000 to 13599999...
2019-02-13 20:22:41.710 [INF] PSQL: Updating from vins 13600000 to 13699999...
2019-02-13 20:30:04.509 [INF] PSQL: Updating from vins 13700000 to 13799999...
2019-02-13 20:37:27.069 [INF] PSQL: Updating from vins 13800000 to 13899999...
2019-02-13 20:44:46.908 [INF] PSQL: Updating from vins 13900000 to 13999999...
2019-02-13 20:52:13.922 [INF] PSQL: Updating from vins 14000000 to 14009507...
2019-02-13 20:52:55.496 [INF] PSQL: Updated 12145709 rows of address table
2019-02-13 20:52:55.497 [INF] PSQL: Indexing addresses table on address...
2019-02-13 20:54:02.934 [INF] PSQL: Indexing addresses table on matching tx hash...
2019-02-13 20:55:04.378 [INF] PSQL: Indexing addresses table on block time...
2019-02-13 20:55:20.370 [INF] PSQL: Indexing addresses table on vout Db ID...
2019-02-13 20:55:48.440 [INF] PSQL: Sync finished at height 318141. Delta: 318142 blocks, 5625488 transactions, 14009523 ins, 20759111 outs, 15058099 addresses
2019-02-13 20:55:48.452 [INF] DATD: PostgreSQL sync ended at height 318141
2019-02-13 20:55:48.489 [INF] SQLT: Current best block (chain server):     318329
2019-02-13 20:55:48.489 [INF] SQLT: Current best block (sqlite block DB):  318141
2019-02-13 20:55:48.489 [INF] SQLT: Current best block (stakedb):          318141
2019-02-13 20:55:48.499 [INF] PSQL: Processing blocks 318142 to 318329...
2019-02-13 20:55:53.045 [INF] SQLT: Scanning blocks 318142 to 318329 (41558 live)...
2019-02-13 20:56:08.580 [INF] PSQL: (  2 blk/s,   34 tx/s,   86 vin/sec,  145 vout/s)
2019-02-13 20:56:28.767 [INF] PSQL: (  1 blk/s,   25 tx/s,   73 vin/sec,   86 vout/s)
2019-02-13 20:56:51.221 [INF] PSQL: (  4 blk/s,   64 tx/s,  145 vin/sec,  216 vout/s)
2019-02-13 20:56:57.575 [INF] SQLT: Rescan finished successfully at height 318329.
2019-02-13 20:56:57.576 [INF] SQLT: resyncDBWithPoolValue completed in 1m9.086893442s
2019-02-13 20:56:57.576 [INF] DATD: SQLite sync ended at height 318329
2019-02-13 20:56:57.682 [INF] PSQL: Pre-fetching project fund balance at height 318329...
2019-02-13 20:57:12.678 [INF] PSQL: Dcur2mcGjmENx4DhNqDctW5wJCVyT3Qeqkx: 60092 spent totalling 157503.278934 DCR, 258901 unspent totalling 610562.156022 DCR
2019-02-13 20:57:12.680 [INF] PSQL: Caching address receive count for address Dcur2mcGjmENx4DhNqDctW5wJCVyT3Qeqkx: count = 318993 at block 318329.
2019-02-13 20:57:12.681 [INF] PSQL: Avg. speed: 35 tx/s, 127 vout/s
2019-02-13 20:57:12.681 [INF] PSQL: Sync finished at height 318329. Delta: 188 blocks, 2947 transactions, 7202 ins, 10676 outs, 13406 addresses
2019-02-13 20:57:12.681 [INF] DATD: PostgreSQL sync ended at height 318329
2019-02-13 20:57:12.694 [INF] DATD: Mainchain sync complete.
2019-02-13 20:57:12.694 [INF] DATD: All ready, at height 318329.
2019-02-13 20:57:17.361 [INF] EXPR: Pre-populating the charts data. This may take a minute...
2019-02-13 20:57:22.405 [INF] SQLT: Current best block (chain server):     318330
2019-02-13 20:57:22.406 [INF] SQLT: Current best block (sqlite block DB):  318329
2019-02-13 20:57:22.406 [INF] SQLT: Current best block (stakedb):          318329
panic: send on closed channel

goroutine 113568345 [running]:
github.com/decred/dcrdata/v4/db/dcrpg.(*ChainDB).SyncChainDB.func4(0xc025d8c410)
	/home/dmigwi/work/app/golang/src/github.com/decred/dcrdata/db/dcrpg/sync.go:196 +0x53
github.com/decred/dcrdata/v4/db/dcrpg.(*ChainDB).SyncChainDB(0xc00027a870, 0x10994c0, 0xc00024a0c0, 0x109f4e0, 0xc0aaa48930, 0x0, 0x0, 0xc00a1cc300, 0x0, 0x0, ...)
	/home/dmigwi/work/app/golang/src/github.com/decred/dcrdata/db/dcrpg/sync.go:218 +0x548
github.com/decred/dcrdata/v4/db/dcrpg.(*ChainDB).SyncChainDBAsync(0xc00027a870, 0x10994c0, 0xc00024a0c0, 0xc01866e480, 0x109f4e0, 0xc0aaa48930, 0xc000000000, 0x0, 0xc00a1cc300)
	/home/dmigwi/work/app/golang/src/github.com/decred/dcrdata/db/dcrpg/sync.go:110 +0xbb
github.com/decred/dcrdata/v4/db/dcrpg.(*ChainDBRPC).SyncChainDBAsync(0xc0002720c0, 0x10994c0, 0xc00024a0c0, 0xc01866e480, 0x109f4e0, 0xc0aaa48930, 0x0, 0x0, 0xc00a1cc300)
	/home/dmigwi/work/app/golang/src/github.com/decred/dcrdata/db/dcrpg/pgblockchain.go:272 +0xb7
created by main._main.func10
	/home/dmigwi/work/app/golang/src/github.com/decred/dcrdata/main.go:776 +0x2b8

```

**Comment by dmigwi** [comment]
This the piece of code that is causing the above error:
```Golang
	// Safely send sync status updates on barLoad channel, and set the channel
	// to nil if it was closed or the buffer is full.
	sendProgressUpdate := func(p *dbtypes.ProgressBarLoad) {
		if barLoad == nil {
			return
		}
		select {
		case barLoad <- p:
		default:
			log.Debugf("(*ChainDB).SyncChainDB: barLoad chan closed or full. Halting sync progress updates.")
			barLoad = nil
		}
	}
```

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/1011
