### ISSUE TITLE
lite mode: panic on startup

### ISSUE THREAD

**Issue by dajohi** [decred/dcrdata#1058]
$ ./v4
2019-02-28 15:55:00.508 [INF] DATD: Log folder:  /home/dcrdata/.dcrdata/logs/testnet3
2019-02-28 15:55:00.508 [INF] DATD: Config file: /home/dcrdata/.dcrdata/dcrdata.conf
2019-02-28 15:55:00.508 [INF] DATD: dcrdata version 4.0.0-pre+dev (Go version go1.12)
2019-02-28 15:55:00.508 [INF] DATD: Running in "Lite" mode with only SQLite backend and limited functionality.
2019-02-28 15:55:00.590 [INF] RPCC: Established connection to RPC server dcrd-node-01:19109
2019-02-28 15:55:00.593 [INF] DATD: Connected to dcrd (JSON-RPC API v5.0.0) on TestNet3
2019-02-28 15:55:00.594 [WRN] SQLT: Block summary table is empty.
2019-02-28 15:55:00.594 [WRN] SQLT: Stake info table is empty.
2019-02-28 15:55:00.594 [INF] SKDB: Loading ticket pool DB. This may take a minute...
2019-02-28 15:55:00.613 [INF] SKDB: badger: All 0 tables opened in 0s
2019-02-28 15:55:00.615 [INF] SKDB: Loading all ticket pool diffs...
2019-02-28 15:55:00.616 [INF] SKDB: Creating new stake DB.
2019-02-28 15:55:00.620 [INF] SKDB: Advancing ticket pool DB to tip via diffs...
2019-02-28 15:55:00.621 [INF] SKDB: Pre-populating live ticket cache and computing pool value...
2019-02-28 15:55:00.621 [INF] DATD: SQLite DB successfully opened: dcrdata.sqlt.db
2019-02-28 15:55:00.621 [WRN] SQLT: Block summary table is empty.
2019-02-28 15:55:00.621 [WRN] SQLT: Stake info table is empty.
2019-02-28 15:55:00.621 [INF] SQLT: SQLite block summary table height:  -1
2019-02-28 15:55:00.621 [INF] SQLT: SQLite stake info table height:     -1
2019-02-28 15:55:00.621 [INF] SQLT: StakeDatabase height:               0
2019-02-28 15:55:00.625 [WRN] SQLT: Block summary table is empty.
2019-02-28 15:55:00.633 [INF] EXPR: Mean Voting Blocks calculated: 1006
2019-02-28 15:55:00.686 [INF] EXPR: Starting WebsocketHub run loop.
2019-02-28 15:55:00.686 [INF] PUBS: Starting WebsocketHub run loop.
2019-02-28 15:55:00.688 [WRN] SQLT: Block summary table is empty.
2019-02-28 15:55:00.698 [INF] PUBS: Stopping websocket hub.
2019-02-28 15:55:00.698 [INF] EXPR: Stopping websocket hub.
2019-02-28 15:55:00.698 [ERR] EXPR: close channel already closed. This should not happen.
2019-02-28 15:55:00.699 [ERR] EXPR: Do not send on stopPing channel, only close it.
2019-02-28 15:55:00.704 [INF] DATD: Closing connection to dcrd.
2019-02-28 15:55:00.704 [INF] DATD: Bye!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc7ced4]

goroutine 1 [running]:
main._main(0x1217fe0, 0xc000071d00, 0x0, 0x0)
        /home/dcrdata/git/dcrdata/main.go:617 +0x21c4
main.main()
        /home/dcrdata/git/dcrdata/main.go:55 +0x82

**Comment by chappjc** [comment]
Yeah, we don't really bother with "lite" mode too much.  Will fix this but you'll need to run in full mode with `--pg`.

**Comment by chappjc** [comment]
@dajohi Resolved by https://github.com/decred/dcrdata/pull/1059.  But lite mode is pretty useless these days.

**Comment by dajohi** [comment]
time to change the default to full mode then :)
