### ISSUE TITLE
panic on ctrl C

### ISSUE THREAD

**Issue by dajohi** [decred/dcrdata#1074]
```
panic: send on closed channel

goroutine 11 [running]:
github.com/decred/dcrdata/v4/stakedb.(*ChainMonitor).BlockConnectedSync(0xc00e26f130, 0xc0032b0200, 0x0, 0x0)
        /home/dcrdata/git/dcrdata/stakedb/chainmonitor.go:55 +0x147
github.com/decred/dcrdata/v4/notification.(*collectionQueue).processBlock(0xc0000feaa0, 0xc009fc4370)
        /home/dcrdata/git/dcrdata/notification/ntfnhandlers.go:136 +0x141
github.com/decred/dcrdata/v4/notification.superQueue()
        /home/dcrdata/git/dcrdata/notification/ntfnhandlers.go:255 +0x564
created by github.com/decred/dcrdata/v4/notification.MakeNodeNtfnHandlers
        /home/dcrdata/git/dcrdata/notification/ntfnhandlers.go:270 +0x39

```

**Comment by chappjc** [comment]
Mmm.  BlockConnectedSync was a hack.  Originally the closer of the block channel was responsible for sending on it.  But then I needed to have synchronous execution, so I wrapped it with BlockConnectedSync.  This should be refactored. The closer should be the sender

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/1083
