### ISSUE TITLE
lite mode: panic on startup: main.go:568

### ISSUE THREAD

**Issue by Junxin-Huo** [decred/dcrdata#1299]
release v4.1.0

./dcrdata 
2019-04-30 17:07:43.535 [INF] DATD: Log folder:  /Users/xxxx/Library/Application Support/Dcrdata/logs/testnet3
2019-04-30 17:07:43.535 [INF] DATD: Config file: /Users/xxxx/Library/Application Support/Dcrdata/dcrdata.conf
2019-04-30 17:07:43.535 [INF] DATD: dcrdata version 4.1.0-pre+dev (Go version go1.12.4)
2019-04-30 17:07:43.535 [INF] DATD: Running in "Lite" mode with only SQLite backend and limited functionality.
2019-04-30 17:07:43.573 [INF] RPCC: Established connection to RPC server 127.0.0.1:9109
2019-04-30 17:07:43.575 [INF] DATD: Connected to dcrd (JSON-RPC API v5.0.0) on TestNet3
2019-04-30 17:07:43.583 [WRN] SQLT: Block summary table is empty.
2019-04-30 17:07:43.583 [WRN] SQLT: Stake info table is empty.
2019-04-30 17:07:43.585 [INF] SKDB: Loading ticket pool DB. This may take a minute...
2019-04-30 17:07:43.590 [INF] SKDB: badger: All 0 tables opened in 0s
2019-04-30 17:07:43.601 [INF] SKDB: Loading all ticket pool diffs...
2019-04-30 17:07:43.602 [INF] SKDB: Successfully loaded 0 ticket pool diffs
2019-04-30 17:07:43.635 [INF] SKDB: Advancing ticket pool DB to tip via diffs...
2019-04-30 17:07:43.635 [INF] SKDB: Pre-populating live ticket cache and computing pool value...
2019-04-30 17:07:43.635 [INF] DATD: SQLite DB successfully opened: dcrdata.sqlt.db
2019-04-30 17:07:43.635 [WRN] SQLT: Block summary table is empty.
2019-04-30 17:07:43.635 [WRN] SQLT: Stake info table is empty.
2019-04-30 17:07:43.635 [INF] SQLT: SQLite block summary table height:  -1
2019-04-30 17:07:43.635 [INF] SQLT: SQLite stake info table height:     -1
2019-04-30 17:07:43.635 [INF] SQLT: StakeDatabase height:               0
2019-04-30 17:07:43.635 [WRN] SQLT: Block summary table is empty.
2019-04-30 17:07:43.686 [INF] AGDB: 1 agenda records (agendas) were updated
2019-04-30 17:07:43.722 [INF] DATD: Closing connection to dcrd.
2019-04-30 17:07:43.722 [INF] DATD: Bye!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x488dbf3]

goroutine 1 [running]:
main._main(0x4ea6b20, 0xc00003fc80, 0x0, 0x0)
	/Users/xxxx/go/src/github.com/decred/dcrdata/main.go:568 +0x2173
main.main()
	/Users/xxxx/go/src/github.com/decred/dcrdata/main.go:58 +0x82

**Comment by chappjc** [comment]
Lite mode is not supported, and has been removed on `master`.  For release-4.1.0, run dcrdata with the `--pg` switch and carefully read the README section https://github.com/decred/dcrdata#configuring-postgresql-important-seriously-read-this

**Comment by Junxin-Huo** [comment]
Thanks a lot! 😄
