### ISSUE TITLE
db/cache: panic momentarily after startup

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#1330]
```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/decred/dcrdata/db/cache.ChartUints.Avg(0xc068658000, 0x54147, 0x5ac00, 0xffffffffffffffff, 0x0, 0xc064006000)
        /home/jonathan_chappelow/github/decred/dcrdata/db/cache/charts.go:172 +0x99
github.com/decred/dcrdata/db/cache.(*ChartData).Lengthen(0xc0000bd8c0, 0x0, 0x0)
        /home/jonathan_chappelow/github/decred/dcrdata/db/cache/charts.go:430 +0x695
github.com/decred/dcrdata/db/cache.(*ChartData).Update(0xc0000bd8c0)
        /home/jonathan_chappelow/github/decred/dcrdata/db/cache/charts.go:718 +0x24f
github.com/decred/dcrdata/db/cache.(*ChartData).Load(0xc0000bd8c0, 0xc031de47c0, 0x31)
        /home/jonathan_chappelow/github/decred/dcrdata/db/cache/charts.go:584 +0x110
main._main(0x13cfd40, 0xc0000ae2c0, 0x0, 0x0)
        /home/jonathan_chappelow/github/decred/dcrdata/main.go:1117 +0x4913
main.main()
        /home/jonathan_chappelow/github/decred/dcrdata/main.go:59 +0x82
```

**Comment by buck54321** [comment]
I have to admit I'm a little stumped on this one. Any more issues?

**Comment by chappjc** [comment]
I've not seen it since.  Must be a race to the pathological condition.  Let's keep the issue opened and I'll keep an eye out for it again.  It's only on startup so it's not critical.

**Comment by chappjc** [comment]
Just got it again, this time on simnet:

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/decred/dcrdata/db/cache.ChartUints.Avg(0xc00b481cc0, 0x21, 0x28, 0xffffffffffffffff, 0x0, 0xc01fdab860)
	/home/jon/github/decred/dcrdata/db/cache/charts.go:199 +0x99
github.com/decred/dcrdata/db/cache.(*ChartData).Lengthen(0xc0099b01b0, 0x0, 0x0)
	/home/jon/github/decred/dcrdata/db/cache/charts.go:461 +0x6e6
github.com/decred/dcrdata/db/cache.(*ChartData).Update(0xc0099b01b0)
	/home/jon/github/decred/dcrdata/db/cache/charts.go:758 +0x24f
github.com/decred/dcrdata/db/cache.(*ChartData).Load(0xc0099b01b0, 0xc00a2b0390, 0x2e)
	/home/jon/github/decred/dcrdata/db/cache/charts.go:623 +0x110
main._main(0x13d7ea0, 0xc0004b81c0, 0x0, 0x0)
	/home/jon/github/decred/dcrdata/main.go:1119 +0x48f4
main.main()
	/home/jon/github/decred/dcrdata/main.go:59 +0x82
```

**Comment by chappjc** [comment]
I uncovered a couple bugs while poking around.  I'll assign this to myself unless you've already got patch brewing @buck54321

**Comment by buck54321** [comment]
I've got one too. I'll open a PR and see if you've got the same.

**Comment by chappjc** [comment]
Resolve by https://github.com/decred/dcrdata/pull/1384
