### ISSUE TITLE
fresh sync on simnet consistently hangs (Pi related)

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#1380]
A fresh sync on simnet consistently hangs (sometimes git is in the task manager, and sometimes it is not):

```
goroutine 1 [syscall, 1 minutes]:
syscall.Syscall6(0xf7, 0x1, 0x4f3b, 0xc009bbcac0, 0x1000004, 0x0, 0x0, 0x107e580, 0x4d3801, 0xc00bf020c0)
	/home/jon/go112/src/syscall/asm_linux_amd64.s:44 +0x5
os.(*Process).blockUntilWaitable(0xc00be3c7e0, 0x4, 0x28, 0x0)
	/home/jon/go112/src/os/wait_waitid.go:31 +0x98
os.(*Process).wait(0xc00be3c7e0, 0x1264050, 0x1264058, 0x1264048)
	/home/jon/go112/src/os/exec_unix.go:22 +0x39
os.(*Process).Wait(...)
	/home/jon/go112/src/os/exec.go:125
os/exec.(*Cmd).Wait(0xc00bb71e40, 0x0, 0x0)
	/home/jon/go112/src/os/exec/exec.go:474 +0x61
os/exec.(*Cmd).Run(0xc00bb71e40, 0xc00becf980, 0xc0000a2700)
	/home/jon/go112/src/os/exec/exec.go:318 +0x5c
os/exec.(*Cmd).CombinedOutput(0xc00bb71e40, 0x10c90e0, 0x3, 0xc00becf8c0, 0x3, 0x3)
	/home/jon/go112/src/os/exec/exec.go:534 +0xf8
github.com/dmigwi/go-piparser/proposals.(*Parser).readCommandOutput(0xc0001f0ff0, 0x10c90e0, 0x3, 0xc00becf8c0, 0x3, 0x3, 0xc009bbcd48, 0xc009bbcd88, 0xa40a97, 0xc00bef0cb0)
	/home/jon/go/pkg/mod/github.com/dmigwi/go-piparser/proposals@v0.0.0-20190426030541-8412e0f44f55/parser.go:383 +0x85
github.com/dmigwi/go-piparser/proposals.(*Parser).proposal(0xc0001f0ff0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jon/go/pkg/mod/github.com/dmigwi/go-piparser/proposals@v0.0.0-20190426030541-8412e0f44f55/parser.go:279 +0x127
github.com/dmigwi/go-piparser/proposals.(*Parser).ProposalsHistory(0xc0001f0ff0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/jon/go/pkg/mod/github.com/dmigwi/go-piparser/proposals@v0.0.0-20190426030541-8412e0f44f55/parser.go:243 +0x94
github.com/decred/dcrdata/db/dcrpg.(*ChainDB).PiProposalsHistory(0xc000116120, 0xc00bee9600, 0x1, 0x1)
	/home/jon/github/decred/dcrdata/db/dcrpg/pgblockchain.go:1241 +0x85b
main._main(0x13d7ea0, 0xc00021e180, 0x0, 0x0)
	/home/jon/github/decred/dcrdata/main.go:1101 +0x46a8
main.main()
	/home/jon/github/decred/dcrdata/main.go:59 +0x82
```

This is related to issue https://github.com/decred/dcrdata/issues/1374

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/1381
