### ISSUE TITLE
panic: disconnect blocks failed

### ISSUE THREAD

**Issue by Junxin-Huo** [decred/dcrdata#1535]
When I run the dcrdata at testnet. The program crashed and shows like:

2019-08-26 04:26:33.965 [INF] SKDB: Reorganize started. NEW head block 0000003a198fff05d3fc4d1cbc7b6b81a7f41b3b0208cccb6fe996bbfa31ed04 at height 253529.
2019-08-26 04:26:33.965 [INF] SKDB: Reorganize started. OLD head block 0000002376b6a43230cfc07d9c84c9e3b380ff089bb3110f58b41b00933125e3 at height 253528.
2019-08-26 04:26:33.965 [WRN] SKDB: StakeDatabase height is 253502, expected 253528. Rewinding as needed to complete reorg from ancestor at 253527
panic: disconnect blocks failed: tip height 253502, expected 253527

goroutine 492001 [running]:
github.com/decred/dcrdata/stakedb.(*ChainMonitor).switchToSideChain(0xc00a994040, 0xc00f87e6e0, 0x33, 0xc0030bf140, 0x2, 0x2)
	/root/go/pkg/mod/github.com/decred/dcrdata/stakedb@v1.0.2/chainmonitor.go:121 +0x92b
github.com/decred/dcrdata/stakedb.(*ChainMonitor).ReorgHandler(0xc00a994040)
	/root/go/pkg/mod/github.com/decred/dcrdata/stakedb@v1.0.2/chainmonitor.go:178 +0x40f
created by main._main
	/blockchain1/dcrdata-release-v4.1.0/main.go:1215 +0x4767

**Comment by Junxin-Huo** [comment]
I use the dcrdata version `v4.1.4` . Is this the cash reason?

**Comment by chappjc** [comment]
Yes.  The 4.x series isn't supported.  See the Release Status table in the Readme
