### ISSUE TITLE
websockethub: goroutine leak

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#329]
we end up with countless goroutines stuck here:

goroutine 71451 [chan receive, 333 minutes]:
github.com/dcrdata/dcrdata/explorer.(*explorerUI).RootWebsocket.func1.1(0xc429ab9a40, 0xc4388a2840)
        /home/jon/go/src/github.com/dcrdata/dcrdata/explorer/websockethandlers.go:37 +0xa0
created by github.com/dcrdata/dcrdata/explorer.(*explorerUI).RootWebsocket.func1
        /home/jon/go/src/github.com/dcrdata/dcrdata/explorer/websockethandlers.go:36 +0x18c

**Comment by chappjc** [comment]
this was expected behaviour with open countless open connections, as a mis-configured load balancer may cause

**Comment by chappjc** [comment]
was not expected behaviour, but fixed in PR #413
