### ISSUE TITLE
charts data causes panic in lite mode

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#549]
In lite mode:

```
panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa0fa87]

goroutine 1 [running]:
github.com/decred/dcrdata/db/dcrpg.(*ChainDB).GetPgChartsData(0x0, 0xc42ece4510, 0x1, 0x1)
	/home/jon/go/src/github.com/decred/dcrdata/db/dcrpg/pgblockchain.go:843 +0x37
github.com/decred/dcrdata/explorer.(*explorerUI).prePopulateChartsData(0xc43142e340)
	/home/jon/go/src/github.com/decred/dcrdata/explorer/explorer.go:248 +0xb4
github.com/decred/dcrdata/explorer.New(0xf2d7c0, 0xc4204e8f60, 0xf2bc60, 0x0, 0x0, 0xc43556e0a0, 0x13, 0x1, 0xc4200c6fa0)
	/home/jon/go/src/github.com/decred/dcrdata/explorer/explorer.go:231 +0x680
main.mainCore(0x0, 0x0)
	/home/jon/go/src/github.com/decred/dcrdata/main.go:305 +0x138b
main.main()
	/home/jon/go/src/github.com/decred/dcrdata/main.go:558 +0x26
```

The line number is slightly off, but the line is this:

```go
tickets, err := RetrieveTicketsPriceByHeight(pgb.db, pgb.chainParams.StakeDiffWindowSize)
```

In lite mode `pgb` is nil.

**Comment by chappjc** [comment]
resolved by PR https://github.com/decred/dcrdata/pull/550
