### ISSUE TITLE
nil pointer: main.go:357 

### ISSUE THREAD

**Issue by JFixby** [decred/dcrdata#614]
Current master
Log:
```
2018-08-15 20:09:49.910 [INF] DATD: Log folder:  C:\Users\JCode\AppData\Local\Dcrdata\logs\mainnet
2018-08-15 20:09:49.910 [INF] DATD: Config file: D:\GOWS\dev-s\dcrdata.conf
2018-08-15 20:09:49.910 [INF] DATD: dcrdata version 3.0.0 (Go version go1.10.2)
2018-08-15 20:09:49.910 [INF] DATD: Running in "Lite" mode with only SQLite backend and limited functionality.
2018-08-15 20:09:50.002 [INF] RPCC: Established connection to RPC server localhost:9109
2018-08-15 20:09:50.003 [INF] DATD: Connected to dcrd (JSON-RPC API v3.3.0) on MainNet
2018-08-15 20:09:50.006 [INF] SKDB: Loading ticket pool DB. This may take a minute...
2018-08-15 20:09:50.377 [INF] SKDB: Loading all ticket pool diffs...
2018-08-15 20:10:09.017 [INF] SKDB: Advancing ticket pool DB to tip via diffs...
2018-08-15 20:10:09.418 [INF] SKDB: Pre-populating live ticket cache and computing pool value...
2018-08-15 20:10:19.256 [INF] DATD: SQLite DB successfully opened: dcrdata.sqlt.db
2018-08-15 20:10:19.267 [INF] EXPR: Mean Voting Blocks calculated: 7860
2018-08-15 20:10:19.287 [INF] EXPR: Signals unsupported on windows
2018-08-15 20:10:19.287 [INF] EXPR: Starting WebsocketHub run loop.
2018-08-15 20:10:19.299 [INF] SQLT: Current best block (chain server):     265787
2018-08-15 20:10:19.300 [INF] SQLT: Current best block (sqlite block DB):  265787
2018-08-15 20:10:19.300 [INF] SQLT: Current best block (stakedb):          265787
2018-08-15 20:10:19.300 [INF] DATD: SQLite sync ended at height 265787
2018-08-15 20:10:19.300 [INF] DATD: PostgreSQL sync ended at height -1
2018-08-15 20:10:19.300 [INF] EXPR: Stopping mempool monitor
2018-08-15 20:10:19.300 [INF] EXPR: Stopping websocket hub.
2018-08-15 20:10:19.300 [ERR] EXPR: Do not send on stopPing channel, only close it.
2018-08-15 20:10:19.732 [INF] DATD: Closing connection to dcrd.
2018-08-15 20:10:19.733 [INF] DATD: Bye!
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xae5240]

goroutine 1 [running]:
main.mainCore(0x0, 0x0)
	D:/GOWS/src/github.com/decred/dcrdata/main.go:357 +0x1650
main.main()
	D:/GOWS/src/github.com/decred/dcrdata/main.go:593 +0x2d

Process finished with exit code 2
```

**Comment by JFixby** [comment]
Seems like it happens right after the sync was completed.

**Comment by chappjc** [comment]
ah, mf.  Thank you for testing lite mode.
