### ISSUE TITLE
badger: Unclosed iterator at time of Txn.Discard

### ISSUE THREAD

**Issue by robinsonking** [decred/dcrdata#619]
When I ran dcrd and dcrdata first time on windows10 x64,the dcrdata crushed immidiately.
2018-08-16 11:29:35.099 [INF] DATD: Running in "Lite" mode with only SQLite backend and limited functionality.
2018-08-16 11:29:35.104 [DBG] RPCC: Attempting to connect to dcrd RPC localhost:9109 as user admin using certificate located in C:\Users\mayn\AppData\Local\Dcrd\rpc.cert
2018-08-16 11:29:35.157 [INF] RPCC: Established connection to RPC server localhost:9109
2018-08-16 11:29:35.158 [INF] DATD: Connected to dcrd (JSON-RPC API v3.3.0) on MainNet
2018-08-16 11:29:35.172 [WRN] SQLT: Block summary DB is empty.
2018-08-16 11:29:35.172 [WRN] SQLT: Stake info DB is empty.
2018-08-16 11:29:35.172 [INF] SKDB: Loading ticket pool DB. This may take a minute...
2018-08-16 11:29:35.198 [INF] SKDB: Loading all ticket pool diffs...
2018-08-16 11:29:35.199 [INF] DATD: Closing connection to dcrd.
2018-08-16 11:29:35.199 [INF] DATD: Bye!
panic: Unclosed iterator at time of Txn.Discard.

goroutine 1 [running]:
github.com/decred/dcrdata/vendor/github.com/dgraph-io/badger.(*Txn).Discard(0xc04249a090)
        C:/Go/Projects/GPPROJECT/src/github.com/decred/dcrdata/vendor/github.com/dgraph-io/badger/transaction.go:428 +0xe3
github.com/decred/dcrdata/vendor/github.com/dgraph-io/badger.(*DB).View(0xc04203dc00, 0xc047690f28, 0x0, 0x0)
        C:/Go/Projects/GPPROJECT/src/github.com/decred/dcrdata/vendor/github.com/dgraph-io/badger/transaction.go:567 +0x14f
github.com/decred/dcrdata/stakedb.LoadAllPoolDiffs(0xc04203dc00, 0xd56e80, 0x20, 0x0, 0x0, 0x0)
        C:/Go/Projects/GPPROJECT/src/github.com/decred/dcrdata/stakedb/ticketpool.go:176 +0x71
github.com/decred/dcrdata/stakedb.NewTicketPool(0xc0424eb0b0, 0x30, 0xd46e45, 0x10, 0x0, 0x0, 0x0)
        C:/Go/Projects/GPPROJECT/src/github.com/decred/dcrdata/stakedb/ticketpool.go:82 +0x344
github.com/decred/dcrdata/stakedb.NewStakeDatabase(0xc042054780, 0x1405680, 0xc0424eb0b0, 0x30, 0x40, 0x1bd, 0x192, 0x1)
        C:/Go/Projects/GPPROJECT/src/github.com/decred/dcrdata/stakedb/stakedb.go:234 +0x195
github.com/decred/dcrdata/db/dcrsqlite.newWiredDB(0xc04215e1c0, 0xc04219a800, 0xc042054780, 0x1405680, 0xc0424eb0b0, 0x30, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Go/Projects/GPPROJECT/src/github.com/decred/dcrdata/db/dcrsqlite/apisource.go:56 +0x14d
github.com/decred/dcrdata/db/dcrsqlite.InitWiredDB(0xc042077c00, 0xc04219a800, 0xc042054780, 0x1405680, 0xc0424eb0b0, 0x30, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Go/Projects/GPPROJECT/src/github.com/decred/dcrdata/db/dcrsqlite/apisource.go:101 +0xf7
main.mainCore(0x0, 0x0)
        C:/Go/Projects/GPPROJECT/src/github.com/decred/dcrdata/main.go:132 +0xc0c
main.main()
        C:/Go/Projects/GPPROJECT/src/github.com/decred/dcrdata/main.go:595 +0x2d

**Comment by chappjc** [comment]
Please try the proposed fix in PR https://github.com/decred/dcrdata/pull/620.
It's interesting we haven't hit this error before, but most of the devs are working in Linux or Mac.  It may be the windows go runtime was cleaning things up in a different order that revealed this issue.

**Comment by robinsonking** [comment]
OK，it works，thanks！
